# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot = {
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    blacklistedKernelModules = [ "dvb_usb_rtl28xxu" ];
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd = { 
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
      kernelModules = [ ];
      luks.devices."luks-3936540f-f974-4ade-ad40-df40c5accb08".device = "/dev/disk/by-uuid/3936540f-f974-4ade-ad40-df40c5accb08";
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/6619917d-d682-4420-a592-344001f70e61";
      fsType = "ext4";
    };
    "/boot" = { 
      device = "/dev/disk/by-uuid/257B-67A6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  };
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  
  # workaround hack to get newer hardware working until unstable releases 2.0.3
  nixpkgs.overlays = [
    (final: prev: {
      rtl-sdr-osmocom = prev.rtl-sdr-osmocom.overrideAttrs (_old: {
          version = "2.0.3";
  
          src = prev.fetchFromGitHub {
  	  owner = "osmocom";
  	  repo = "rtl-sdr";
  	  rev = "v2.0.3";
  	  hash = "sha256-U9kFG7Fare4swx53fWvYgoV9zmrogyGQ+a1u6Qi8PZ4=";
        };
      });
      rtl-sdr = final.rtl-sdr-osmocom;
    })
    (final: prev:
      let
        gnuradioMinimalNoUhdOsmosdr =
          prev.gnuradioMinimal // {
            pkgs = prev.gnuradioMinimal.pkgs.overrideScope (
              _final: grPrev: {
                osmosdr = grPrev.osmosdr.overrideAttrs (old: {
                  cmakeFlags = (old.cmakeFlags or []) ++ [
                    "-DENABLE_UHD=OFF"
                    "-DENABLE_SOAPY=OFF"
                  ];
                });
              }
            );
          };
      in {
        gqrx = prev.gqrx.override {
          gnuradioMinimal = gnuradioMinimalNoUhdOsmosdr;
        };
      })
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    graphics = {
      enable = true;
      enable32Bit = true;
    };
    rtl-sdr = {
      enable = true;
      package = pkgs.rtl-sdr-osmocom;
    };
  };
}
